parse_config:
  raw_binding_map:
    "&soft_off":
      tap: $$mdi:power$$

    # Bluetooth
    "&bt BT_SEL 0":
      tap: $$mdi:bluetooth-connect$$
      hold: 1
    "&bt BT_SEL 1":
      tap: $$mdi:bluetooth-connect$$
      hold: 2
    "&bt BT_SEL 2":
      tap: $$mdi:bluetooth-connect$$
      hold: 3
    "&bt BT_SEL 3":
      tap: $$mdi:bluetooth-connect$$
      hold: 4
    "&bt BT_SEL 4":
      tap: $$mdi:bluetooth-connect$$
      hold: 5
    "&bt_clr_0":
      tap: $$mdi:bluetooth-off$$
    "&bt_clr_1":
      tap: $$mdi:bluetooth-off$$
    "&bt_clr_2":
      tap: $$mdi:bluetooth-off$$
    "&bt_clr_3":
      tap: $$mdi:bluetooth-off$$
    "&bt_clr_4":
      tap: $$mdi:bluetooth-off$$

