manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tku137
      url-base: https://github.com/tku137
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: flake-zmk-module
      remote: tku137
      revision: yads-dongle-support
    - name: zmk-dongle-screen
      remote: tku137
      revision: my-setup
  self:
    path: config
