manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: anywhy-io
      url-base: https://github.com/anywhy-io
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: flake-zmk-module
      remote: anywhy-io
      revision: 796f7a689e8d9a53fec0ad0f3cd24db37136eca9
  self:
    path: config
